services:
  api:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/app/data
      - ./vectordb:/app/vectordb
      - ./reprebot.db:/app/reprebot.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"

  streamlit:
    build: .
    command: bash -c "cd ../.. && streamlit run src/app/main.py"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_HOST=${API_HOST}
    ports:
      - "8501:8501"
